DELETE http://localhost:8080/clear
Accept: application/json

###

DELETE http://localhost:8080/clear/api/test/path
Accept: application/json

###

GET http://localhost:8080/config/api/test/path
Accept: application/json

###

POST http://localhost:8080/config/api/test/path
Accept: application/json
Content-Type: application/json

{
  "static": false,
  "handler": "(req, res) => res.sendStatus(403)",
  "response": {
    "status": 203,
    "body": null
  }
}
###

GET http://localhost:8080/api/test/path
Accept: application/json

###
